// GENERATED by scripts/derive-filter-options.ts — do not edit by hand.
// Regenerate with `npm run prebuild`.

export const CATEGORIES = [
  "Beef",
  "Breakfast",
  "Chicken",
  "Dessert",
  "Goat",
  "Lamb",
  "Miscellaneous",
  "Pasta",
  "Pork",
  "Seafood",
  "Side",
  "Starter",
  "Vegan",
  "Vegetarian"
] as const;
export type Category = (typeof CATEGORIES)[number];

export const AREAS = [
  "Algerian",
  "Australian",
  "British",
  "Canadian",
  "Chinese",
  "Croatian",
  "Egyptian",
  "Filipino",
  "Greek",
  "Irish",
  "Italian",
  "Jamaican",
  "Japanese",
  "Kenyan",
  "Malaysian",
  "Mexican",
  "Moroccan",
  "Polish",
  "Portuguese",
  "Russian",
  "Saudi Arabian",
  "Spanish",
  "Syrian",
  "Thai",
  "Tunisian",
  "Turkish",
  "Ukrainian",
  "Uruguayan",
  "Vietnamese"
] as const;
export type Area = (typeof AREAS)[number];
