// Run via `npm run prebuild`. Emits src/lib/domain/filter-options.generated.ts.
//
// Categories come straight from list.php?c=list (TheMealDB never caps that call).
// Areas cannot: list.php?a=list returns ~190 candidates, most of which are empty —
// filter.php?a=Afghan returns {"meals":null}, verified. Unioning strArea across the
// 14 filter.php?c= responses would be the same silent-truncation bug D-15 exists to
// eliminate, one layer down (those responses cap at 100). So each area candidate is
// probed once with filter.php?a={area} and kept only if it returns a non-empty result.
// See DECISIONS.md OQ-2 / OQ-2a — this script's location, output path and on-failure
// behaviour are pinned there.
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const BASE_URL = 'https://www.themealdb.com/api/json/v1/1';
const OUTPUT_PATH = path.resolve(import.meta.dirname, '../src/lib/domain/filter-options.generated.ts');

interface CategoryListResponse {
	meals: { strCategory: string }[] | null;
}

interface AreaListResponse {
	meals: { strArea: string }[] | null;
}

interface FilterResponse {
	meals: unknown[] | null;
}

function delay(ms: number): Promise<void> {
	return new Promise((resolve) => setTimeout(resolve, ms));
}

/** TheMealDB rate-limits bursts (429) — retry a few times with backoff before giving up. */
async function fetchJson<T>(url: string, attempt = 1): Promise<T> {
	const response = await fetch(url);
	if (response.status === 429 && attempt <= 5) {
		await delay(500 * attempt);
		return fetchJson<T>(url, attempt + 1);
	}
	if (!response.ok) throw new Error(`${url} responded with ${response.status}`);
	return (await response.json()) as T;
}

async function deriveCategories(): Promise<string[]> {
	const { meals } = await fetchJson<CategoryListResponse>(`${BASE_URL}/list.php?c=list`);
	return (meals ?? []).map((meal) => meal.strCategory).sort();
}

const PROBE_CONCURRENCY = 3;

async function isPopulatedArea(area: string): Promise<boolean> {
	const { meals } = await fetchJson<FilterResponse>(`${BASE_URL}/filter.php?a=${encodeURIComponent(area)}`);
	return Boolean(meals && meals.length > 0);
}

/** One request per candidate either way — concurrency only shortens the wall clock. */
async function deriveAreas(): Promise<string[]> {
	const { meals } = await fetchJson<AreaListResponse>(`${BASE_URL}/list.php?a=list`);
	const candidates = (meals ?? []).map((meal) => meal.strArea);

	const survivors: string[] = [];
	for (let i = 0; i < candidates.length; i += PROBE_CONCURRENCY) {
		const batch = candidates.slice(i, i + PROBE_CONCURRENCY);
		const results = await Promise.all(batch.map(isPopulatedArea));
		batch.forEach((area, j) => {
			if (results[j]) survivors.push(area);
		});
	}
	return survivors.sort();
}

function render(categories: string[], areas: string[]): string {
	return `// GENERATED by scripts/derive-filter-options.ts — do not edit by hand.
// Regenerate with \`npm run prebuild\`. See DECISIONS.md OQ-2 / OQ-2a.

export const CATEGORIES = ${JSON.stringify(categories, null, 2)} as const;
export type Category = (typeof CATEGORIES)[number];

export const AREAS = ${JSON.stringify(areas, null, 2)} as const;
export type Area = (typeof AREAS)[number];
`;
}

async function main() {
	try {
		const [categories, areas] = await Promise.all([deriveCategories(), deriveAreas()]);
		await mkdir(path.dirname(OUTPUT_PATH), { recursive: true });
		await writeFile(OUTPUT_PATH, render(categories, areas), 'utf-8');
		console.log(`derive-filter-options: wrote ${categories.length} categories and ${areas.length} areas.`);
	} catch (err) {
		const message = err instanceof Error ? err.message : String(err);
		try {
			await readFile(OUTPUT_PATH, 'utf-8');
			console.warn(`derive-filter-options: fetch failed (${message}); keeping the committed artifact.`);
		} catch {
			console.error(
				`derive-filter-options: fetch failed (${message}) and no committed artifact exists at ${OUTPUT_PATH}.`
			);
			process.exitCode = 1;
		}
	}
}

await main();
